ElvaRivle/Misc/BugFixes
becarselman/ant-colony-pharaoh-frontend pull request #27
Opened 2023-06-23 14:37 UTC by ElvaRivle

ElvaRivle/Misc/BugFixes

--------------------------------------------------------------------
 MAIN
 * fixed all bugs that we discussed last time
--------------------------------------------------------------------
 OTHER
 * /
--------------------------------------------------------------------
 TODO
 * logout functionality

2023-06-26 08:35 UTC, AntMarkoLovric requested changes

2023-06-26 08:35 UTC, AntMarkoLovric commented on src/components/sidebar/Sidebar.js
> +                        <a onClick={(e) => e.preventDefault()}>
move function outside of jsx

2023-06-26 08:35 UTC, AntMarkoLovric commented on src/routing/protectedRoute.js
> +        <div style={{width: "100%"}}>
please don't use inline style

2023-06-26 08:35 UTC, AntMarkoLovric commented on src/routing/publicRoute.js
> +                <div style={{width: "100%"}}>
same as the comment before regarding inline style

2023-06-26 08:35 UTC, AntMarkoLovric commented on src/routing/publicRoute.js
> +    let token = localStorage.getItem("accessToken")
what happens if you get invalid token

2023-06-29 12:15 UTC, becarselman requested changes

2023-06-29 12:15 UTC, becarselman commented on src/components/sidebar/Sidebar.js
> +                        <a onClick={(e) => e.preventDefault()}>
you are resolve comment but don't fix anything

2023-06-29 12:15 UTC, becarselman commented on src/routing/protectedRoute.js
> +        <div style={{width: "100%"}}>
same

2023-06-29 12:15 UTC, becarselman commented on src/routing/publicRoute.js
> +                <div style={{width: "100%"}}>
same

2023-06-30 06:55 UTC, becarselman approved these changes

2023-06-30 06:55 UTC, merged