FEATURE/TariikMVP/AssignDevelopersv2 Work in Progress
becarselman/ant-colony-pharaoh-frontend pull request #34
Opened 2023-07-03 12:04 UTC by TarikVelic

--------------------------------------------------------------------
 MAIN
 * Added new style for assign developers
 * Added select which contains part time and full time options
 * Small changes in code --------------------------------------------------------------------
 OTHER
 * ///// --------------------------------------------------------------------

2023-07-03 12:59 UTC, AntMarkoLovric requested changes

2023-07-03 12:59 UTC, AntMarkoLovric commented on src/components/formFields/MultiSelect.js
> +          onChange={(e) => e.stopPropagation()}
move this outside of jsx

2023-07-03 12:59 UTC, AntMarkoLovric commented on src/components/formFields/MultiSelect.js
> +                  onClick={() => onRemoveDeveloper(developer.value)}
move this also

2023-07-03 12:59 UTC, AntMarkoLovric commented on src/components/formFields/MultiSelect.js
> +        {item.value.map((developerId) => {
move map outside of jsx

2023-07-03 12:59 UTC, AntMarkoLovric commented on src/components/projects/components/AddProjectsModal/AddProjectsModal.js
> +            onClick={() => removeDeveloper(developer._id)}
move this also

2023-07-10 08:47 UTC, becarselman approved these changes

2023-07-10 09:30 UTC, melcidar approved these changes

2023-07-10 11:26 UTC, AntMarkoLovric approved these changes

2023-07-11 08:15 UTC, closed without merging