Forgot Password
becarselman/ant-colony-pharaoh-frontend pull request #7
Opened 2023-05-04 11:38 UTC by meliha01

--------------------------------------------------------------------
 MAIN
 * this is the look of forgot password page --------------------------------------------------------------------
 OTHER
 * ignore changes in actions, because nothing is set --------------------------------------------------------------------
 
![image](https://github.com/becarselman/ant-colony-pharaoh-frontend/assets/119449806/6e478600-9b50-4898-9b89-e8b8d6c7b119)

* the look of reset password
![image](https://github.com/becarselman/ant-colony-pharaoh-frontend/assets/119449806/72a2cb06-78f3-4534-8495-52f238466a36)

2023-05-10 09:17 UTC, becarselman requested changes

2023-05-10 09:17 UTC, becarselman commented on src/components/loginform/LoginForm.js
> +           <a className="forgot-password" onClick={() => navigate('/forgot-password')} href="#">Forgot password?</a>
why you using a tag and then onClick. You can specify route in href and it will navigate to /forgot-password

2023-05-10 09:17 UTC, becarselman commented on src/sagas/forgotPasswordSaga.js
> +  console.log("aaaaaaaaa");
remove console log

2023-05-10 09:17 UTC, becarselman commented on src/sagas/forgotPasswordSaga.js
> +    console.error('An error occurred:', error);
remove conosle.error

2023-05-10 09:17 UTC, becarselman commented on src/sagas/forgotPasswordSaga.js
> +    console.error('An error occurred:', error);
If you want to display error you can use notification popups.

2023-05-16 08:19 UTC, becarselman requested changes

2023-05-16 08:19 UTC, becarselman commented on src/components/forgotpassword/ForgotPassword.js
> +function ForgotPassword({ actions }) {
please use arrow function

2023-05-16 08:19 UTC, becarselman commented on src/components/forgotpassword/ForgotPassword.js
> +      const response = await dispatch(passwordRequest({ email: email }));
we don't need dispatch because we have mapDispatchToProps in container.js

2023-05-16 08:19 UTC, becarselman commented on src/components/resetpassword/resetPassword.js
> +      await dispatch(resetPasswordRequest(token, newPassword));
same as prev comment

2023-05-16 08:19 UTC, becarselman commented on src/service/authService.js
> +    const response = await axios.post(`http://localhost:5000/reset-password/${token}`, { newPassword }, {
use this url from env

2023-05-18 07:04 UTC, becarselman approved these changes

2023-05-18 07:04 UTC, becarselman commented on src/components/forgotpassword/ForgotPassword.js
> +    console.log(actions)
remove console.log

2023-05-18 19:32 UTC, TarikVelic approved these changes

2023-05-19 07:17 UTC, merged